module.exports = {
  "system": "./src/plugin/provide/system/index.js",
  "system.authority.rules": "./src/views/system/authority/rules/index",
  "system.authority.field": "./src/views/system/authority/field/index",
  "system.authority.data": "./src/views/system/authority/data/index",
  "system.dept": "./src/views/system/dept/index",
  "system.menu": "./src/views/system/menu/index",
  "system.role": "./src/views/system/role/index",
  "system.post": "./src/views/system/post/index",
  "system.user": "./src/views/system/user/index",
  "system.interface": "./src/views/system/interface/index",
  "system.report": "./src/views/system/report/index",
  "system.report.review": "./src/views/system/report/preview/index",
  "system.report.authority": "./src/views/system/report/authority/index",
};
